alias ls="exa --icons --group-directories-first"
alias ll="exa --icons --group-directories-first -l"
alias lt="exa --icons --group-directories-first -T"
alias c="clear"
alias lg="lazygit"
alias s="kitty +kitten ssh"
